---
title: "Public Engagement"
output: html_document
---
<br>


# Knowledge Exchange (KE) Events

***2025***

The PI was invited and participated in the Department for Education (DfE) roundtable on School Attendance (January 2025)


***2024***

In collaboration with the Scottish Government and Education Scotland, the PI and Co-I organised the KE event ”Promoting School Attendance: Questions for Research, Policy, and Practice” at the University of Strathclyde (September 2024).

The PI and Co-I organised the Symposium "Understanding the multifaceted impact of pupil absences on academic achievement: Timing, trajectories, psychosocial pathways and sociodemographic differences" at the BPS Psychology of Education Annual Conference at the University of Cambridge (September 2024).

We organised the Knowledge Exchange events "Understanding School Attendance, Education, and Labour Market Outcomes" summarising findings from our Nuffield Foundation project and providing key policy and practice implications in Cardiff (23rd April) and Manchester (25th April).


***2023***

We organised the event "Absenteeism and exclusion research - What next?" for policymakers and practitioners together with Prof Gillean McCluskey and Dr Annie Taylor (University of Edinburgh) from the Excluded Lives project (06 June).


***2022***

Together with Poverty Alliance and General Teaching Council for Scotland (GTCS), we organised the Webinar [School absences and the poverty-related attainment gap](https://www.strath.ac.uk/humanities/events/schoolabsencesandthepovertyrelatedattainmentgap/) 


***2021***

Together with Dr Markus Gehrsitz (University of Strathclyde), we organised the Strathclyde Engage Event [Data Can Tell Us ‘What Works’ in Education: Insights from Quantitative Education Research] (https://www.engage.strath.ac.uk/event/804).

***2019***

We presented first results from our project at the Engage Strathclyde event [Who is Missing Out on School? The Role of School Absenteeism in the Poverty-Related Attainment Gap](https://www.engage.strath.ac.uk/event/604).

<br>

# Invited Talks/Keynotes

***2025***

The PI has given the Keynote ”Understanding the causes
and consequences of school absenteeism” at the Tusla Education Welfare Service Conference, Kilkenny, Ireland (June 2025).

The PI was invited to give the talk ”The short- and long-term consequences of school absences” in the National Foundation for Educational Research (NFER) Seminar Series (June 2025)

The PI has given the keynote "Understanding school attendance, educational attainment, and labour market outcomes" at the Annual Scottish Educational Psychology Conference (March 2025)


***2024***

The PI was invited to give the talk ”The short- and long-term consequences of school
absences” to the West Partnership Attendance Specialist Network (December 2024)

The PI and Co-I were invited to give the talk ”The short- and long-term consequences of school
absences” at the Education Endowment Foundation Tuesday Twilight Seminar (September 2024)

The PI has given the Keynote ”School Attendance Problems:
Causes, Trends, and Impacts” at the OECD Peer-learning discussion I – Monitoring of school attendance problems and early leaving from education and training at the OECD in Paris (September 2024)

The PI and Co-I have given the Keynote "Understanding school attendance, educational attainment, and labour market outcomes” at  the CQIS Attendance Conference at South Lanarkshire Council (September 2024)

The PI and Co-I were invited to present findings from their project at the Nuffield Foundation event [The impact of school absence, school closure and learning loss: What can be done](https://www.nuffieldfoundation.org/events/the-impact-of-school-absence). A recording of the event is available.

The PI has given the talk "Socioeconomic status, school absences, and educational and labour market outcomes to the Scottish Division of Educational Psychology (SDEP) Non-Attendance Working Group (March 2024)


***2023***

PI and Co-I presented a summary of our absenteeism research in the Scottish Government Educational Research Seminar Series (May 2023). We also provided a policy brief for dissemination among civil servants.

We provided the Keynote "Determinants and Consequences of School Absenteeism" at the [Attendance Symposium](https://blogs.glowscotland.org.uk/glowblogs/public/fvwlric/uploads/sites/7616/2023/02/03100640/Attendance-Symposium-Brochure.pdf), a professional learning event for educators, aimed at addressing school attendance problems to improve life outcomes for children and young people in Scotland (March 2023). The event was organised by the Forth Valley and West Lothian Regional Improvement Collaborative: 


***2022***

The PI presented our research in the Scottish Quantitative Education Workshop at the University of Glasgow

***2021***

The PI was invited to give a talk in the School of Education at the University of Glasgow and presented a summary of our current project findings.

<br>

# Videos & podcasts

***2022***

Moderated by Prof Donald Christie, this webinar presents research findings on the role of school absences in the poverty related attainment gap in Scotland, and the implications for policy and practice.

<iframe width="560" height="315" src="https://www.youtube.com/embed/JNORvpbQERw" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<br>

***2021***

Prof Claire Cassidy (University of Strathclyde) interviewed us for the School of Education’s [podcast series “Meet an academic”](https://anchor.fm/strathclyde-education/episodes/Podcast-21-Meet-an-academic-Dr--Edward-Sosu-and-Dr--Markus-Klein-e11an8n)

We published a [podcast](https://sway.office.com/x5EJ7G2hrOjsTgnG?ref=Link) summarising our first and second research brief as part of Education Scotland’s Signposting Equity Issue 12. 

<br>


# Policy Impact

***2025***

The [Scottish Government's School attendance Guidance Working Group](https://www.gov.scot/publications/school-attendance-guidance-working-group-terms-of-reference/) draws on our research evidence to support development of refreshed guidance on school attendance

[Ofsted](https://www.gov.uk/government/consultations/improving-the-way-ofsted-inspects-education/improving-the-way-ofsted-inspects-education-supporting-evidence-base) has used our research evidence to inform and develop the design of their toolkits, the proposed inspection methodology and inspector training.


***2023***

We were invited to present evidence at the [06 December meeting of the All Party Parliamentary Group (APPG) for Parental Participation in Education with a focus on school attendance](https://www.parentkind.org.uk/research-and-policy/education-policy/policy-in-england/all-party-parliamentary-group-for-england/appg-6th-december-2023)

We submitted [Written Evidence](https://committees.parliament.uk/writtenevidence/117933/pdf/) to the UK Parliament Education Committee on persistent absence and support for disadvantaged pupils.



<br>

# Media & Blogs

***2025***

[School Health Pulse](https://schoolhealthpulse.com/) has published the article "Even moderate absences, below the 10% threshold and for valid reasons, can significantly impact GCSE outcomes" based on our paper in [PLOS One](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0306716)


The PI was interviewed by the Sunday Post for their article [Present and correct? School experts say over-focus on attendance fails to tackle absenteeism and could be harmful to children](https://www.sundaypost.com/fp/school-attendance/) (February 2025)


***2024***

The TES Magazine has covered our Nuffield Foundation report in the article [Absence during school transition ‘is especially harmful’](https://www.tes.com/magazine/news/general/pupil-absence-during-school-transition-most-harmful) (September 2024)

The PI was interviewed on the radio show 'Toronto Today with Greg Brady' on 640 Toronto (September 2024).

We have written the article [The harmful effects of absence stretch beyond school](https://www.tes.com/magazine/analysis/general/harmful-effects-pupil-absence-go-beyond-school) for TES magazine (May 2024).

Our [BERJ article](https://bera-journals.onlinelibrary.wiley.com/doi/10.1002/berj.3992) on the long-term consequences of school absences for educational and labour market outcomes was cited in The Conversation article [School suspensions are on the rise – secondary schools can tackle this by creating a sense of belonging](https://theconversation.com/school-suspensions-are-on-the-rise-secondary-schools-can-tackle-this-by-creating-a-sense-of-belonging-229155) (May 2024)

***2023***

Our views on data reporting in Scotland have been discussed in the TES article [Absence is a UK-wide problem. Here’s how to tackle it](https://www.tes.com/magazine/analysis/general/pupil-absence-improve-school-attendance) (November 2023)

We have written the blog post [Persistent absence from school is a growing threat to children's education](https://theconversation.com/persistent-absence-from-school-is-a-growing-threat-to-childrens-education-201501) highlighting the increase of absence rates during the pandemic and summarising our research on the determinatns and consequences of school absenteeism (March 2023)


***2022***

Our paper published in Review of Education was discussed in the Newsbreak (Philippines) article [More than 40% of Peoria Public School students were chronically absent in 2021](https://www.newsbreak.com/news/2727934122886/more-than-40-of-peoria-public-school-students-were-chronically-absent-in-2021).

Our paper published in Children and Youth Services Review was cited in the blog post [School attendance problems are complex, and our solutions need to be as well](https://theconversation.com/school-attendance-problems-are-complex-and-our-solutions-need-to-be-as-well-189849).

Our paper published in AERA Open was discussed in TES article [Authorised school absence ‘equally detrimental’ to pupils](https://www.tes.com/magazine/news/general/authorised-school-absence-equally-detrimental-pupils). 

***2021***

Our research brief "Socioeconomic Inequalities in School Attendance in Scotland" was discussed in the report [The Poverty-related Attainment Gap: A review of the evidence](https://www.povertyalliance.org/wp-content/uploads/2021/02/The-Poverty-related-Attainment-Gap-A-Review-of-the-Evidence-2.pdf) by Poverty Alliance and the Robertson Trust. 

Our research brief "Socioeconomic disparities in school absenteeism after the first wave of COVID-19 school closures in Scotland" was discussed in The Herald article [Agenda: Tackling the disadvantage faced by young people locked in poverty](https://www.heraldscotland.com/news/19054348.agenda-tackling-disadvantage-faced-young-people-locked-poverty/).

***2020***

Our project is discussed in the GTCS publication [Teaching Scotland (Issue 86)](https://edition.pagesuite-professional.co.uk/html5/reader/production/default.aspx?pubname=&edid=217750e9-ff63-45d8-8f1a-8e4e3fd6a35f).

We published the blog post [School Attendance and the Poverty-related Attainment Gap](https://www.strath.ac.uk/humanities/schoolofeducation/blog/schoolattendanceandthepoverty-relatedattainmentgap/) for the Strathclyde Institute of Education summarising our results findings. 

<br>


# Conference presentations

***2025***

"Socioeconomic status, school absences, and academic achievement - A causal mediation analysis" was presented at the ISA Spring Meeting 2025, Milan (March 2025)

***2024***

“Does the impact of pupil absences depend on their timing?" was presented at the American Educational Research Association (AERA) Annual Conference, Philadelphia (April 2024)


***2023***

“Does the impact of pupil absences depend on their timing?" was presented at the Society for Longitudinal and Lifecourse Studies (SLLS) Annual Conference, Ludwig Maximillian University of Munich (October 2023)


“School absenteeism trajectories and their consequences for achievement" was presented at the British Educational Research ASsociation (BERA) Conference, Aston University (September 2023)


“School absenteeism trajectories and their consequences for achievement" was presented at the European Conference for Educational Research (ECER), University of Glasgow (August 2023)


“School absenteeism trajectories and their consequences for achievement" was presented at Children of the noughties: a conference to celebrate 21 years of the Millennium Cohort Study, London (June 2023)


***2022***

“School absenteeism and academic achievement – Heterogeneity across type of absence and family socioeconomic status” was presented at the Scottish Educational Research Association (SERA) Conference in Ayr, Scotland (November 2022).

“Family socioeconomic status and academic achievement: the mediating role of school absenteeism” was presented at the International Network for School Attendance (INSA) Conference in Egmont aan Zee, Netherlands (October 2022).

“School absences in secondary schooling and adolescents’ post-school destinations – Evidence from the Scottish Longitudinal Study” was presented at the Transitions in Youth (TIY) Conference in Naples, Italy (September 2022).

“School absences in secondary schooling and adolescents’ post-school destinations – Evidence from the Scottish Longitudinal Study” was presented at the European Association for Research on Adolescence (EARA) Conference in Dublin, Ireland (August 2022).


***2021***

“Family background and academic achievement: An investigation into the mediating role of school absenteeism” was presented at the European Consortium for Sociological Research (ECSR) Annual Conference 2021.

“Are school leavers’ post-school destinations associated with their school attendance during secondary education? was presented at the Society for Longitudinal and Lifecourse (SLLS) Annual Conference 2021.

“Family socioeconomic status and educational achievement: Examining the mediating role of school absenteeism” was presented at the BPS Psychology of Education Conference 2021. 

“School absenteeism and academic achievement: Is missing out on school more detrimental to students from lower socioeconomic backgrounds?” was presented at the European Conference on Educational Research (ECER) Annual Conference 2021. 

“School absenteeism and academic achievement: Is missing out on school more detrimental for students from lower socioeconomic backgrounds” was presented at the ISA RC28 Spring Meeting 2021 in Turku (virtual conference). 


***2019***

“School absenteeism and educational attainment: Is missing out on school more detrimental to students from lower socioeconomic backgrounds? was presented at the Society for Longitudinal and Lifecourse Studies (SLLS) Annual Conference 2019 in Potsdam, Germany.

“Who is missing out on school? Exploring socioeconomic inequalities in school absenteeism” was presented at the European Conference on Educational Research (ECER) 2019 in Hamburg, Germany. 


