---
title: "Publications"
output: html_document
---
<br> 


# Peer-reviewed journal articles

[Dräger, J., Klein, M., & Sosu, E. M. (2024). Trajectories of school absences across compulsory schooling and their impact on children’s academic achievement: An analysis based on linked longitudinal survey and school administrative data. PloS one, 19(8), e0306716.](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0306716)

**Abstract:** Prior research has identified that school absences harm children’s academic achievement. However, this literature is focused on brief periods or single school years and does not consistently account for the dynamic nature of absences across multiple school years. This study examined dynamic trajectories of children’s authorised and unauthorised absences throughout their compulsory school career in England. It investigated the consequences of these absence trajectories for children’s achievement at the end of compulsory schooling. We analyse linked administrative data on children’s absences and achievement from the National Pupil Database and survey data from the Millennium Cohort Study for a representative sample of children born in 2000/2001 in England (N = 7218). We used k-means clustering for longitudinal data to identify joint authorised-unauthorised absence trajectories throughout compulsory schooling and a regression-with-residuals approach to examine the link between absence trajectories and achievement. We identified five distinct absence trajectories: (1) ‘Consistently Low Absences’, (2) ‘Consistently Moderate Authorised Absences’, (3) ‘Moderately Increasing Unauthorised Absences’, (4) ‘Strongly Increasing Unauthorised Absences’, and (5) ‘Strongly Increasing Authorised Absences’. We found substantial differences between trajectory groups in GCSE achievement, even when accounting for significant risk factors of school absences. Compared to ‘Consistently Low Absences’, ‘Strongly Increasing Unauthorised Absences’ reduced achievement by -1.23 to -1.48 standard deviations, while ‘Strongly Increasing Authorised Absences’ reduced achievement by -0.72 to -1.00 SD for our continuous outcomes. ‘Moderately Increasing Unauthorised Absences’ (-0.61 to -0.70 SD) and ‘Consistently Moderate Authorised Absences’ (-0.13 to -0.21 SD) also negatively affected achievement compared to ‘Consistently Low Absences’. Our research underscores the critical importance of examining entire trajectories of absenteeism and differentiating between types of absences to fully grasp their associations with academic outcomes and design targeted interventions accordingly.<br> <br>

[Dräger, J., Klein, M., & Sosu, M. (2024). The long-term consequences of early school absences for educational attainment and labour market outcomes, British Educational Research Journal, 00, 1–19. https://doi.org/10.1002/berj.3992](https://bera-journals.onlinelibrary.wiley.com/doi/10.1002/berj.3992)

**Abstract:** School absences can negatively impact a child's schooling, including the loss of teacher-led lessons, peer interactions, and, ultimately, academic achievement. However, little is known about the long-term consequences of school absences for overall educational attainment and labour market outcomes. In this paper, we used data from the 1970 British Cohort Study to examine long-term associations between school absences in late childhood and individuals’ educational attainment, social class, unemployment and earnings at age 42 while adjusting for a comprehensive set of confounders. Our findings show that school absences are associated with lower educational attainment but are not associated with social class destination except for increasing the likelihood of being out of the labour force after adjusting for confounders. Individuals who missed five days of school at age 10 were 5.2% more likely to have obtained no qualifications and 4.1% more likely to be out of the labour force. However, we did not find a significant association between school absences and individuals’ earnings or duration of unemployment. Our findings suggest that the detrimental consequences of school absences persist beyond schooling into adulthood. Overall, this study highlights the importance of addressing school absenteeism to promote educational and labour market participation over the life course.<br> <br>

[Klein, M., & Sosu, M. (2024). School absences, academic achievement, and adolescents’ post-school destinations. Oxford Review of Education, DOI: 10.1080/03054985.2024.2308520](https://www.tandfonline.com/doi/full/10.1080/03054985.2024.2308520?src=exp-la)

**Abstract:** Most research on the consequences of school absenteeism has focused on academic achievement but not post-school outcomes. Using the Scottish Longitudinal Study (n = 2,941), we investigated the link between overall absences, truancy, sickness-related absences, and upper secondary school leavers’ post-school destinations. We also examined how upper secondary school achievement explains these associations. Overall school absences during the first year of upper secondary schooling decreased the likelihood of continuing further and higher education, but increased the likelihood of being employed, or not being in education, employment, or training (NEET). Sickness absences and truancy also reduced the likelihood of pursuing further and higher education. Truancy did not significantly increase the risk of NEET, but sickness absences did. Both absence types did not significantly influence the likelihood of being employed. Academic achievement mediated 78%-100% of the link between overall absences, sickness absences or truancy and entry into further and higher education versus being employed. While achievement explained 38%–55% of the link between all absences and further and higher education versus NEET, it did not explain the link between absences and NEET versus being employed. The study emphasises the necessity of reducing both unexcused and excused school absences and mitigating their effects.<br> <br>



[Klein, M., & Sosu, M. (2024). School attendance and academic achievement: Understanding variation across family socioeconomic status. Sociology of Education, 91(1), 58-75](https://doi.org/10.1177/00380407231191541)

**Abstract:** Studies consistently show detrimental effects of school absences on pupils’ achievement. However, due to an accumulation of multiple risks, school absenteeism may be more harmful to achievement among pupils from lower socioeconomic status (SES). Using a sample of upper secondary students from the Scottish Longitudinal Study (n = 3,135), we investigated whether the association between absences (overall, sickness, and truancy) and achievement in high-stakes exams varied by family SES dimensions (parental education, class, free school meal registration, and housing). When considering overall absences and truancy, results show no statistically significant differences across SES groups. However, sickness absences were more harmful to lower than higher SES students' achievement. Differences between the most and least disadvantaged groups were found on all SES dimensions except for parental education.<br> <br>


[Klein, M., Sosu, E. M., & Dare, S. (2022). School Absenteeism and Academic Achievement: Does the Reason for Absence Matter? AERA Open, 8, 23328584211071115.](https://journals.sagepub.com/doi/full/10.1177/23328584211071115)  

**Abstract:** Studies consistently show associations between school absences and academic achievement. However, questions remain about whether this link depends on the reason for children’s absence. Using a sample of the Scottish Longitudinal Study (n = 4,419), we investigated whether the association between school absenteeism and achievement in high-stakes exams at the end of compulsory and postcompulsory schooling varies with the reason for absence. In line with previous research, our findings show that overall absences are negatively associated with academic achievement at both school stages. Likewise, all forms of absences (truancy, sickness absence, exceptional domestic circumstances, and family holidays) are negatively associated with achievement at the end of compulsory and postcompulsory schooling. First difference regressions confirm these negative associations, except for family holidays. These findings suggest that, in addition to lost instruction, other mechanisms such as behavioral, health-related, and psychosocial pathways may account for the association between absenteeism and achievement. The findings have implications for designing tailored absenteeism interventions to improve pupils’ academic achievement.<br> <br>   

[Sosu, E. M., Dare, S., Goodfellow, C., & Klein, M. (2021). Socioeconomic status and school absenteeism: A systematic review and narrative synthesis. Review of Education, 9(3), e3291.](https://bera-journals.onlinelibrary.wiley.com/doi/full/10.1002/rev3.3291)  

**Abstract:** School absenteeism is detrimental to life course outcomes and is known to be socioeconomically stratified.  However, the link between socioeconomic status (SES) and school absence is complex given the multidimensional nature of both family SES (e.g., income, education, occupational status) and absenteeism (e.g., truancy, sickness, suspension).  Despite the vast literature on socioeconomic inequalities in school attendance, no systematic review on SES and school absenteeism exists.  This study systematically reviewed and provides a narrative synthesis of journal articles (n = 55) published between 1998 to 2019 on the association between SES dimensions and forms of absenteeism.  The majority of studies from high-income contexts found an association between SES and absenteeism in the expected direction, albeit on average with small effect sizes.  Studies largely confirmed these findings among populations at risk of school absence and those from low- and middle-income countries.  There was greater evidence for an association between absenteeism and SES measured at the family than the school level.  Studies using SES measures of financial resources (e.g., free or reduced-price lunch) provided more evidence for this association than studies measuring sociocultural resources (e.g., parental education).  There is limited evidence that socioeconomic achievement gaps in absenteeism vary by the reasons for absence. Research on the mediating pathways between SES and absenteeism is sparse.  A key implication is that attempts to address inequalities in educational outcomes must include tackling SES gaps in school attendance.<br> <br>   


[Klein, M., Sosu, E. M., & Dare, S. (2020). Mapping inequalities in school attendance: The relationship between dimensions of socioeconomic status and forms of school absence. Children and Youth Services Review, 118, 105432.](https://www.sciencedirect.com/science/article/pii/S0190740920303698)

**Abstract:** In this article, we investigated whether and to what extent various dimensions of socioeconomic background (parental education, parental class, free school meal registration, housing status, and neighbourhood deprivation) predict overall school absences and different reasons for absenteeism (truancy, sickness, family holidays and temporary exclusion) among 4,620 secondary school pupils in Scotland. Students were drawn from a sample of the Scottish Longitudinal Study comprising linked Census data and administrative school records. Using fractional logit models and logistic regressions, we found that all dimensions of socioeconomic background were uniquely linked to overall absences. Multiple measures of socioeconomic background were also associated with truancy, sickness-related absence, and temporary exclusion. Social housing and parental education had the most pervasive associations with school absences across all forms of absenteeism. Our findings highlight the need to consider the multidimensionality of socioeconomic background in policy and research decisions on school absenteeism. A more explicit focus on narrowing the socioeconomic gap in absenteeism is required to close the inequality gap in educational and post-school outcomes.<br> <br>


# Main Public Output for the [Nuffield Foundation](https://www.nuffieldfoundation.org/)

[Klein, M., Sosu, E. M., Dräger, J., and Perinetti Casoni, V. (2024). Understanding School Attendance, Educational Attainment and Labour Market Outcomes](https://strathprints.strath.ac.uk/90427/)

**Summary:**
Pupil absenteeism has long been a challenge in the UK, especially among disadvantaged children, and this has worsened since the Covid-19 pandemic. In England, the absence rate rose from 4.3% in 2018 to 7.2% in 2024, with similar trends in Wales, Scotland, and Northern Ireland. Socioeconomic disparities in absenteeism have also widened, making it a critical focus for UK education policy. This study explores how absenteeism affects educational attainment and labour market outcomes. Absences are shown to have both short- and long-term negative impacts, with significant negative impacts on national exam performance and future employment prospects. The study finds that absences during key educational transitions, such as from primary to secondary school, are particularly detrimental. While patterns of increasing absences from early primary school onwards are the most damaging, even moderate levels of absenteeism accumulate to harm academic achievement. Both authorised and unauthorised absences equally impact educational outcomes, though unauthorised absences are particularly harmful when they increase over time. The study also found that psychosocial factors, such as educational motivation and risky behaviours, partly explain the negative impact of absenteeism on academic success. The negative effects of absenteeism are consistent across all UK nations and sociodemographic groups, with disadvantaged students more likely to be frequently absent. The findings underscore the need for targeted interventions, such as early support systems, health screenings, and efforts to engage families and schools in addressing absenteeism. Addressing absenteeism at all school stages and across all groups is essential for improving educational and labour market outcomes and breaking the cycle of disadvantage, particularly in the post-pandemic context. In conclusion, addressing pupil absenteeism is essential for enhancing educational outcomes and breaking the cycle of disadvantage. This study provides critical insights for policymakers and educators in the post-pandemic context, emphasizing the need for targeted, stage-specific interventions that address both authorised and unauthorised absences, while also considering the broader psychosocial factors that contribute to absenteeism. <br> <br>


# Policy briefs


[Dräger, J, Klein, M., & Sosu, E. (2023) Trajectories of School Absences and Pupils' Academic Performance. Research Brief. University of Strathclyde](https://pure.strath.ac.uk/ws/portalfiles/portal/179401547/Drager-etal-UoS-2023-Trajectories-of-School-Absences-and-Pupils-Academic-Performance.pdf)

**Key Points:**

- Two-thirds of pupils have consistently low absence trajectories,
while one-third demonstrate some form of moderate to high
absence trajectories over the compulsory schooling period.
- More than one-fourth of pupils have consistently moderate
authorised absences.
- Three smaller groups have moderately increased unauthorised,
strongly increasing authorised, and strongly increasing
unauthorised absences.
- All identified absence trajectories have a detrimental impact
on GCSE achievement in year 11, with increasing unauthorised
absences having the most harmful impact.
- While extreme levels of unauthorised absences are most
detrimental, a narrow policy focus on this absentee group will
miss many students with other absence trajectories, whose
impact is also harmful to achievement.
- The findings emphasise the need for a nuanced approach
to combating absenteeism, including tailored support for
students in different absence trajectory groups.


<br>

[Klein, M., Sosu, E., & Lillywhite, E. (2022) School Absenteeism and Educational Attainment - Evidence from the Scottish Longitudinal Study. Research Brief. University of Strathclyde](https://strathprints.strath.ac.uk/80713/)

**Key Points:**

- School absences are detrimental to educational attainment in national exams at the end of compulsory (S4) and post-compulsory schooling (S5/S6) in Scotland.
- Truancy, sickness-related absences, and absences due to exceptional domestic circumstances each have a unique negative impact on educational attainment at both stages.
- Our findings suggest three additional pathways through which absence may affect academic achievement: a behavioural pathway, a health pathway, and a psychosocial pathway.
- Our research challenges previous assumptions that unexcused absences are more harmful than excused absences and calls for equal emphasis on tackling all forms of school absence.
- Research and interventions need to focus on mitigating the harmful consequences of school absenteeism, considering the reason for absence.

<br>

[Sosu, E., & Klein, M. (2021). Socioeconomic disparities in school absenteeism after the first wave of COVID-19 school closures in Scotland. Research Brief. University of Strathclyde](https://www.researchgate.net/publication/348478558_Socioeconomic_disparities_in_school_absenteeism_after_the_first_wave_of_COVID-19_school_closures_in_Scotland)

**Key Points:**

- Student absences after the first wave of Covid-19 school closures were higher than in previous years 
- Higher rates of absenteeism after school lockdown were due to COVID-19 related reasons 
- Overall, non-Covid-19-related absence rates are similar to trends observed in earlier years 
- Socioeconomic inequalities in school absenteeism were higher post-lockdown than in previous years 
- This increase can be attributed to rising disparities in school absenteeism due to Covid19-related and non-Covid-19 reasons 
- The rise in socioeconomic inequality in nonCovid-19related absenteeism was not only due to higher absence rates among students from the most deprived areas but also due to lower absence rates among students from the least deprived areas 
- Addressing the disproportionate short- and long-term impact of the pandemic on the most vulnerable children needs to be at the forefront of policy agenda 
- We need greater monitoring and evaluation of:
  - inequalities in home learning during the second round of school    closures 
  - inequalities in academic achievement after school reopening 
  - policy interventions designed to mitigate the consequences of Covid-19 on achievement gaps.
  
<br>

[Klein, M., Goodfellow, C., Dare, S., & Sosu, E. (2020). Socioeconomic Inequalities in School Attendance in Scotland: Research Brief. University of Strathclyde.](https://www.researchgate.net/publication/343737573_Socioeconomic_Inequalities_in_School_Attendance_in_Scotland_-_Research_Brief)

**Key points:**

- Absenteeism from school is socially stratified and being absent from school is likely an important contributor to the attainment gap in Scotland.
- All dimensions of socioeconomic background increased the risk of overall absenteeism from school. 
- Pupils from socially rented households, and households with no qualifications are the most likely to be absent from school, and these factors are consistently associated with all forms of absenteeism (overall, sickness based, truancy, temporary exclusion) except family holidays. 
- The association between socioeconomic background and absenteeism did not vary across gender or place of residence (urban vs rural). 
- It is likely that COVID-19 related school closures will exacerbate socioeconomic inequalities in school attendance. 
- There is an urgent need to address socioeconomic inequalities in school absenteeism.

<br>



# Work in progress


Jascha Dräger, Markus Klein, Edward Sosu. Does the impact of pupil absences depend on their timing?. *Revise and resubmit*. A preprint can be accessed [here](https://osf.io/preprints/edarxiv/nwzqh).

Jascha Dräger, Markus Klein, Edward Sosu. Socioeconomic status, school absences, and academic achievement - A causal mediation analysis. *Under review*. A preprint can be accessed [here](https://osf.io/preprints/socarxiv/w4bdc).

Jascha Dräger, Markus Klein, Edward Sosu. The psychosocial pathways betweeen school absenteeism and academic achievement. *In progress*.

Olga Rotar, Valentina Perinetti Casoni, Markus Klein, Edward Sosu. Do pupil absences always hurt achievement equally? An analysis of effect heterogeneity across boys and girls. *In progress*.

Markus Klein, Edward Sosu, Kenvil Souza, and Samara Marta. A systematic review of interventions to reduce school absences. *In progress*.

